spring.application.name=api-salas-de-aula
spring.datasource.url=jdbc:postgresql://localhost:5432/salas_ufsm
spring.datasource.username=postgres
spring.datasource.password=1124

spring.jpa.hibernate.ddl-auto=validate
